sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10"

branches:
  only:
    - /.*/

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test
  
scripts:
  - npm install codecov -g
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
